### ISSUE TITLE
What do __eou__ and __eot__ mean?

### ISSUE THREAD

**Issue by cagdass** [mertaytore/quora_qa_pyarser#2]
https://github.com/mertaytore/quora_qa_pyarser/blob/master/extract.py#L91

&&

https://github.com/mertaytore/quora_qa_pyarser/blob/master/extract.py#L84

**Comment by mertaytore** [comment]
eou stands for 'end of utterance' and it was a small indicator for question's end.
eot stands for 'end of talk' and it was an indicator for answer's end.

 They were useful in another task but since there is no reason for them to exist now, they have been removed.
